[package]
name = "basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metrics = "0.22.0"
metrics-exporter-prometheus = "0.13.0"
metrics-process = { path = "../../" }
rand = "0.8.5"
